language: node_js
node_js:
- "8"
sudo: required
services:
- docker
after_deploy:
- echo "done deploying"
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: $ACCESSKEY
  secret_access_key:
    secure: "$SECRETACCESSKEY"
  region: "eu-west-3"
  app: "aws"
  env: "aws-dev"
  bucket_name: "arn:aws:s3:::elasticbeanstalk-eu-west-3-212773766897"
